apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odl-system
  name: odl-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odl-system
  strategy: {}
  template:
    metadata:
      labels:
        app: odl-system
    spec:
      containers:
      - image: opendaylight/opendaylight:17.2.0
        name: odl-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
