apiVersion: v1
kind: Service
metadata:
  labels:
    app: odl-system
  name: odl-system-service
spec:
  ports:
  - port: 8181 #change to 80
    protocol: TCP
    targetPort: 8181 #change to 80
    nodePort: 30111
  selector:
    app: odl-system
  type: NodePort
